# Generated by Django 5.0.6 on 2024-07-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
